<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExerciseBenchmarkSeeder extends Seeder
{
    public function run(): void
    {
        // If you have FK constraints pointing to this table, you may want to disable checks temporarily.
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('exercise_benchmarks')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $benchmarks = [
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 60,
                'p80' => 50,
                'p70' => 45,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 80,
                'p80' => 70,
                'p70' => 60,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 100,
                'p80' => 90,
                'p70' => 80,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 120,
                'p80' => 110,
                'p70' => 100,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 150,
                'p80' => 130,
                'p70' => 120,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 180,
                'p80' => 160,
                'p70' => 140,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 55,
                'p80' => 50,
                'p70' => 45,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 70,
                'p80' => 65,
                'p70' => 60,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 90,
                'p80' => 80,
                'p70' => 70,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 110,
                'p80' => 100,
                'p70' => 90,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 130,
                'p80' => 120,
                'p70' => 110,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'double_leg_glute',
                'exercise_name' => 'Double leg glute',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 160,
                'p80' => 140,
                'p70' => 130,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 35,
                'p80' => 30,
                'p70' => 27,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 40,
                'p80' => 35,
                'p70' => 32,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 50,
                'p80' => 45,
                'p70' => 40,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 60,
                'p80' => 55,
                'p70' => 48,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 70,
                'p80' => 60,
                'p70' => 55,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 80,
                'p80' => 70,
                'p70' => 65,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 30,
                'p80' => 26,
                'p70' => 23,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 35,
                'p80' => 31,
                'p70' => 28,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 45,
                'p80' => 40,
                'p70' => 36,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 55,
                'p80' => 48,
                'p70' => 44,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 60,
                'p80' => 55,
                'p70' => 50,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_raise',
                'exercise_name' => 'Calf raise',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 70,
                'p80' => 62,
                'p70' => 58,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 16,
                'p80' => 14,
                'p70' => 13,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 20,
                'p80' => 18,
                'p70' => 16,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 25,
                'p80' => 22,
                'p70' => 20,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 30,
                'p80' => 27,
                'p70' => 25,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 35,
                'p80' => 32,
                'p70' => 30,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 40,
                'p80' => 36,
                'p70' => 34,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 14,
                'p80' => 13,
                'p70' => 12,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 18,
                'p80' => 16,
                'p70' => 15,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 22,
                'p80' => 20,
                'p70' => 18,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 27,
                'p80' => 25,
                'p70' => 23,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 32,
                'p80' => 30,
                'p70' => 28,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'lunges',
                'exercise_name' => 'Lunges',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 36,
                'p80' => 34,
                'p70' => 32,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 9,
                'p90' => 40,
                'p80' => 34,
                'p70' => 30,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'male',
                'age_min' => 10,
                'age_max' => 12,
                'p90' => 48,
                'p80' => 42,
                'p70' => 36,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 15,
                'p90' => 55,
                'p80' => 48,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'male',
                'age_min' => 16,
                'age_max' => 18,
                'p90' => 60,
                'p80' => 52,
                'p70' => 45,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 9,
                'p90' => 38,
                'p80' => 32,
                'p70' => 28,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'female',
                'age_min' => 10,
                'age_max' => 12,
                'p90' => 44,
                'p80' => 38,
                'p70' => 32,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 15,
                'p90' => 50,
                'p80' => 44,
                'p70' => 38,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat',
                'exercise_name' => 'Squat',
                'gender' => 'female',
                'age_min' => 16,
                'age_max' => 18,
                'p90' => 55,
                'p80' => 48,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'plank',
                'exercise_name' => 'Plank',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 50,
                'p80' => 45,
                'p70' => 40,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'plank',
                'exercise_name' => 'Plank',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 60,
                'p80' => 55,
                'p70' => 50,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'plank',
                'exercise_name' => 'Plank',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 80,
                'p80' => 70,
                'p70' => 65,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'plank',
                'exercise_name' => 'Plank',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 100,
                'p80' => 90,
                'p70' => 80,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'plank',
                'exercise_name' => 'Plank',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 120,
                'p80' => 110,
                'p70' => 100,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'plank',
                'exercise_name' => 'Plank',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 150,
                'p80' => 130,
                'p70' => 120,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'tricep_dips',
                'exercise_name' => 'Tricep dips',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 14,
                'p80' => 11,
                'p70' => 9,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'tricep_dips',
                'exercise_name' => 'Tricep dips',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 18,
                'p80' => 15,
                'p70' => 12,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'tricep_dips',
                'exercise_name' => 'Tricep dips',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 22,
                'p80' => 18,
                'p70' => 15,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'tricep_dips',
                'exercise_name' => 'Tricep dips',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 26,
                'p80' => 22,
                'p70' => 18,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'tricep_dips',
                'exercise_name' => 'Tricep dips',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 30,
                'p80' => 26,
                'p70' => 21,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'tricep_dips',
                'exercise_name' => 'Tricep dips',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 34,
                'p80' => 29,
                'p70' => 24,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 35,
                'p80' => 30,
                'p70' => 27,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 38,
                'p80' => 34,
                'p70' => 30,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 42,
                'p80' => 37,
                'p70' => 34,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 46,
                'p80' => 42,
                'p70' => 38,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 50,
                'p80' => 46,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 52,
                'p80' => 48,
                'p70' => 44,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 32,
                'p80' => 28,
                'p70' => 25,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 36,
                'p80' => 32,
                'p70' => 29,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 40,
                'p80' => 36,
                'p70' => 33,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 44,
                'p80' => 40,
                'p70' => 36,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 48,
                'p80' => 44,
                'p70' => 40,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'skaters',
                'exercise_name' => 'Skaters',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 50,
                'p80' => 46,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 22,
                'p80' => 20,
                'p70' => 18,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 30,
                'p80' => 28,
                'p70' => 26,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 40,
                'p80' => 37,
                'p70' => 35,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 50,
                'p80' => 47,
                'p70' => 45,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 55,
                'p80' => 52,
                'p70' => 50,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 60,
                'p80' => 56,
                'p70' => 54,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 20,
                'p80' => 18,
                'p70' => 16,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 28,
                'p80' => 26,
                'p70' => 24,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 35,
                'p80' => 33,
                'p70' => 31,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 45,
                'p80' => 42,
                'p70' => 40,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 50,
                'p80' => 47,
                'p70' => 45,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'russian_twist',
                'exercise_name' => 'russian twist',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 55,
                'p80' => 52,
                'p70' => 50,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 30,
                'p80' => 27,
                'p70' => 24,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 35,
                'p80' => 32,
                'p70' => 29,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 40,
                'p80' => 37,
                'p70' => 34,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 45,
                'p80' => 42,
                'p70' => 39,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 50,
                'p80' => 47,
                'p70' => 44,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 55,
                'p80' => 52,
                'p70' => 49,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 28,
                'p80' => 25,
                'p70' => 22,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 33,
                'p80' => 30,
                'p70' => 27,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 38,
                'p80' => 35,
                'p70' => 32,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 43,
                'p80' => 40,
                'p70' => 37,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 48,
                'p80' => 45,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'leg_raises',
                'exercise_name' => 'leg raises',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 53,
                'p80' => 50,
                'p70' => 47,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 65,
                'p80' => 60,
                'p70' => 55,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 75,
                'p80' => 70,
                'p70' => 65,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 85,
                'p80' => 80,
                'p70' => 75,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 95,
                'p80' => 90,
                'p70' => 85,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 100,
                'p80' => 95,
                'p70' => 90,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 105,
                'p80' => 100,
                'p70' => 95,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 60,
                'p80' => 55,
                'p70' => 50,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 70,
                'p80' => 65,
                'p70' => 60,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 80,
                'p80' => 75,
                'p70' => 70,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 90,
                'p80' => 85,
                'p70' => 80,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 95,
                'p80' => 90,
                'p70' => 85,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'jumping_jacks',
                'exercise_name' => 'Jumping jacks',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 100,
                'p80' => 95,
                'p70' => 90,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 45,
                'p80' => 42,
                'p70' => 39,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 50,
                'p80' => 47,
                'p70' => 44,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 55,
                'p80' => 52,
                'p70' => 49,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 60,
                'p80' => 57,
                'p70' => 54,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 65,
                'p80' => 62,
                'p70' => 59,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 70,
                'p80' => 67,
                'p70' => 64,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 42,
                'p80' => 39,
                'p70' => 36,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 47,
                'p80' => 44,
                'p70' => 41,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 52,
                'p80' => 49,
                'p70' => 46,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 57,
                'p80' => 54,
                'p70' => 51,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 60,
                'p80' => 57,
                'p70' => 54,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'calf_jumps',
                'exercise_name' => 'Calf jumps',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 65,
                'p80' => 62,
                'p70' => 59,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 70,
                'p80' => 66,
                'p70' => 62,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 80,
                'p80' => 76,
                'p70' => 72,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 90,
                'p80' => 86,
                'p70' => 82,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 100,
                'p80' => 96,
                'p70' => 92,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 110,
                'p80' => 106,
                'p70' => 102,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 120,
                'p80' => 116,
                'p70' => 112,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 68,
                'p80' => 64,
                'p70' => 60,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 78,
                'p80' => 74,
                'p70' => 70,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 86,
                'p80' => 82,
                'p70' => 78,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 96,
                'p80' => 92,
                'p70' => 88,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 104,
                'p80' => 100,
                'p70' => 96,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'arm_circles',
                'exercise_name' => 'arm circles',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 112,
                'p80' => 108,
                'p70' => 104,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 50,
                'p80' => 47,
                'p70' => 44,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 55,
                'p80' => 52,
                'p70' => 49,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 60,
                'p80' => 57,
                'p70' => 54,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 65,
                'p80' => 62,
                'p70' => 59,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 70,
                'p80' => 67,
                'p70' => 64,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 75,
                'p80' => 72,
                'p70' => 69,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 48,
                'p80' => 45,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 53,
                'p80' => 50,
                'p70' => 47,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 58,
                'p80' => 55,
                'p70' => 52,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 63,
                'p80' => 60,
                'p70' => 57,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 68,
                'p80' => 65,
                'p70' => 62,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'toe_raises',
                'exercise_name' => 'toe raises',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 72,
                'p80' => 70,
                'p70' => 67,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 40,
                'p80' => 35,
                'p70' => 30,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 50,
                'p80' => 45,
                'p70' => 40,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 60,
                'p80' => 55,
                'p70' => 50,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 75,
                'p80' => 70,
                'p70' => 65,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 90,
                'p80' => 85,
                'p70' => 80,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 100,
                'p80' => 95,
                'p70' => 90,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 35,
                'p80' => 32,
                'p70' => 28,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 45,
                'p80' => 42,
                'p70' => 38,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 55,
                'p80' => 52,
                'p70' => 48,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 70,
                'p80' => 65,
                'p70' => 60,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 85,
                'p80' => 80,
                'p70' => 75,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'superman_plank',
                'exercise_name' => 'superman plank',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 95,
                'p80' => 90,
                'p70' => 85,
                'unit' => 'seconds',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 28,
                'p80' => 26,
                'p70' => 24,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 34,
                'p80' => 32,
                'p70' => 30,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 40,
                'p80' => 38,
                'p70' => 36,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 46,
                'p80' => 44,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 52,
                'p80' => 50,
                'p70' => 48,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 56,
                'p80' => 54,
                'p70' => 52,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 26,
                'p80' => 24,
                'p70' => 22,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 32,
                'p80' => 30,
                'p70' => 28,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 38,
                'p80' => 36,
                'p70' => 34,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 44,
                'p80' => 42,
                'p70' => 40,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 50,
                'p80' => 48,
                'p70' => 46,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'squat_jumps',
                'exercise_name' => 'Squat jumps',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 54,
                'p80' => 52,
                'p70' => 50,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 70,
                'p80' => 65,
                'p70' => 60,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 80,
                'p80' => 75,
                'p70' => 70,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 95,
                'p80' => 90,
                'p70' => 85,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 110,
                'p80' => 105,
                'p70' => 100,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 120,
                'p80' => 115,
                'p70' => 110,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 130,
                'p80' => 125,
                'p70' => 120,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 65,
                'p80' => 60,
                'p70' => 55,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 75,
                'p80' => 70,
                'p70' => 65,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 90,
                'p80' => 85,
                'p70' => 80,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 105,
                'p80' => 100,
                'p70' => 95,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 115,
                'p80' => 110,
                'p70' => 105,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'mountain_climbers',
                'exercise_name' => 'mountain climbers',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 125,
                'p80' => 120,
                'p70' => 115,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 26,
                'p80' => 24,
                'p70' => 22,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 32,
                'p80' => 30,
                'p70' => 28,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 38,
                'p80' => 36,
                'p70' => 34,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 45,
                'p80' => 43,
                'p70' => 41,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 50,
                'p80' => 48,
                'p70' => 46,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 55,
                'p80' => 53,
                'p70' => 51,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 25,
                'p80' => 23,
                'p70' => 21,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 30,
                'p80' => 28,
                'p70' => 26,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 36,
                'p80' => 34,
                'p70' => 32,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 42,
                'p80' => 40,
                'p70' => 38,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 47,
                'p80' => 45,
                'p70' => 43,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'good_mornings',
                'exercise_name' => 'good mornings',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 52,
                'p80' => 50,
                'p70' => 48,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 20,
                'p80' => 18,
                'p70' => 16,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 24,
                'p80' => 22,
                'p70' => 20,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 30,
                'p80' => 28,
                'p70' => 26,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 36,
                'p80' => 34,
                'p70' => 32,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 42,
                'p80' => 40,
                'p70' => 38,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 46,
                'p80' => 44,
                'p70' => 42,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 18,
                'p80' => 16,
                'p70' => 14,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 22,
                'p80' => 20,
                'p70' => 18,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 28,
                'p80' => 26,
                'p70' => 24,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 34,
                'p80' => 32,
                'p70' => 30,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 40,
                'p80' => 38,
                'p70' => 36,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'renegade_rows',
                'exercise_name' => 'renegade rows',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 44,
                'p80' => 42,
                'p70' => 40,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'male',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 40,
                'p80' => 36,
                'p70' => 32,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'male',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 48,
                'p80' => 44,
                'p70' => 40,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'male',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 58,
                'p80' => 54,
                'p70' => 50,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'male',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 70,
                'p80' => 66,
                'p70' => 62,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'male',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 80,
                'p80' => 76,
                'p70' => 72,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'male',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 90,
                'p80' => 85,
                'p70' => 80,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'female',
                'age_min' => 7,
                'age_max' => 8,
                'p90' => 38,
                'p80' => 34,
                'p70' => 30,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'female',
                'age_min' => 9,
                'age_max' => 10,
                'p90' => 45,
                'p80' => 41,
                'p70' => 37,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'female',
                'age_min' => 11,
                'age_max' => 12,
                'p90' => 54,
                'p80' => 50,
                'p70' => 46,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'female',
                'age_min' => 13,
                'age_max' => 14,
                'p90' => 66,
                'p80' => 62,
                'p70' => 58,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'female',
                'age_min' => 15,
                'age_max' => 16,
                'p90' => 76,
                'p80' => 72,
                'p70' => 68,
                'unit' => 'reps',
            ],
            [
                'exercise_key' => 'shoulder_tap',
                'exercise_name' => 'Shoulder tap',
                'gender' => 'female',
                'age_min' => 17,
                'age_max' => 18,
                'p90' => 85,
                'p80' => 80,
                'p70' => 75,
                'unit' => 'reps',
            ],
        ];

        $now = now();

        // Insert in chunks to avoid hitting max packet limits
        foreach (array_chunk($benchmarks, 500) as $chunk) {
            $payload = array_map(function ($row) use ($now) {
                $row['created_at'] = $now;
                $row['updated_at'] = $now;
                return $row;
            }, $chunk);

            DB::table('exercise_benchmarks')->insert($payload);
        }
    }
}
